import type { Metadata } from "next";
import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { Suspense } from "react";
import { ChatProvider } from "@/context/ChatContext";
import { Socket } from "dgram";
import { SocketProvider } from "@/context/SocketContext";
import { LocationUpdater } from "@/components";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
});

export const metadata: Metadata = {
  title: "Proxichat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${urbanist.variable} antialiased !bg-gray-900`}
      >
        <UserProvider>
            <ChatProvider>
              <Suspense fallback={null}>
                {children}
              </Suspense>
            </ChatProvider>
        </UserProvider>
      </body>
    </html>
  );
}